version: '3'
services:
  backend:
    build: ./backend
    depends_on:
      - nginx

  frontend:
    build: .
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    restart: on-failure
