name: Build and Release Application

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
permissions:
  contents: write
jobs:
  build-mac:
    env:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      TEAM_ID: ${{ secrets.TEAM_ID }}
      SIGN_ID: ${{ secrets.SIGN_ID }}
      APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '22.9.0'
      - name: Install Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERT_BASE64 }}
          BUILD_CERTIFICATE_PASSWORD: ${{ secrets.BUILD_CERT_PASS }}
          BUILD_PROVISION_PROFILE_BASE64:
            ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASS }}

        run: |
          # Create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.provisionprofile
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # Import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # Create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # Import certificate to keychain
          security import $CERTIFICATE_PATH -P "$BUILD_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # Apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Build
        run: |
          mkdir -p bin
          echo "Downloading RMLMapper"
          curl -L https://github.com/RMLio/rmlmapper-java/releases/download/v7.2.0/rmlmapper-7.2.0-r374-all.jar -o bin/mapper.jar

          echo "Building frontend"
          npm run frontend:prod

          echo "Installing python dependencies"
          uv sync

          echo "Building application"
          ./scripts/mac/build.sh

          echo "Preparing application bundle for notarization"
          ./scripts/mac/prepare-bundle.sh

          echo "Notarizing application"
          ./scripts/mac/notarize-bundle.sh

      # Zip the RDFCraft.app so it remains a folder after download
      - name: Create ZIP from .app
        run: |
          cd dist
          zip -r RDFCraft-mac.zip RDFCraft.app

      - name: Upload Mac Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RDFCraft-Mac
          path: dist/RDFCraft-mac.zip

      - name: Cleanup keychain
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
          rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.provisionprofile

  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '22.9.0'

      - name: Build
        run: |
          mkdir -p bin
          echo "Downloading RMLMapper"
          curl -L https://github.com/RMLio/rmlmapper-java/releases/download/v7.2.0/rmlmapper-7.2.0-r374-all.jar -o bin/mapper.jar

          echo "Building frontend"
          npm run frontend:prod

          echo "Installing python dependencies"
          uv sync

          echo "Building application"
          .\.venv\Scripts\python.exe -m nuitka `
            --standalone `
            --onefile `
            --product-version=$env:GITHUB_REF_NAME `
            --file-version=$env:GITHUB_REF_NAME `
            --output-dir=dist `
            --include-data-dir=public=public `
            --include-data-dir=bin=bin `
            --windows-disable-console `
            --product-name=RDFCraft `
            --assume-yes-for-downloads `
            --deployment `
            main.py

          mv dist/main.exe dist/RDFCraft.exe

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RDFCraft-Windows
          path: dist/RDFCraft.exe

  release:
    needs: [build-mac, build-win]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: 'softprops/action-gh-release@v1'
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            artifacts/RDFCraft-Mac/RDFCraft-mac.zip
            artifacts/RDFCraft-Windows/RDFCraft.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
