name: Build Application

on:
  push:
    tags:
      - 'v*'

jobs:
  build-mac:
    # This job runs on macOS
    # It requires just and uv to be installed
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install just
        uses: extractions/setup-just@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '22.9.0'
      - name: Build
        run: |
          just package-mac
      # This will upload the built application to the artifacts application is located at dist/RDFCraft.app
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: RDFCraft
          path: dist/RDFCraft.app

  build-win:
    # This job runs on Windows
    # It requires just and uv to be installed
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install just
        uses: extractions/setup-just@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '22.9.0'
      - name: Build
        run: |
          just package-win
      # This will upload the built application to the artifacts application is located at dist/RDFCraft.exe
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: RDFCraft
          path: dist/RDFCraft.exe
